from sqlalchemy import Column, Integer, String, Float, DateTime, Text, JSON
from datetime import datetime
from ..base import Base

class SmartTraderSignal(Base):
    """Signals generated by Smart Trader system"""
    __tablename__ = "smart_trader_signals"

    id = Column(Integer, primary_key=True, index=True)

    # Signal identification
    composite_id = Column(String(100), unique=True, nullable=False, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    timeframe = Column(String(10), nullable=False)
    direction = Column(String(10), nullable=False)

    # Signal classification
    signal_families = Column(Text)
    signal_names = Column(Text)
    confluence_count = Column(Integer, nullable=False)
    aggregate_strength = Column(Float, nullable=False)

    # Confidence
    base_confidence = Column(Float, nullable=False)
    final_confidence = Column(Float, nullable=False)
    confidence_level = Column(String(10), nullable=False)

    # Deterministic reasoning
    deterministic_reasons = Column(Text)
    merged_features = Column(Text)

    # LLM enhancement
    llm_confidence_adjustment = Column(Float)
    llm_narrative = Column(Text)
    llm_risk_flags = Column(Text)
    llm_model = Column(String(50))
    llm_processing_time_ms = Column(Integer)

    # Trade setup
    entry_price = Column(Float)
    stop_loss = Column(Float)
    target = Column(Float)
    risk_reward_ratio = Column(Float)
    quantity = Column(Integer)

    # Trade review
    llm_review_recommendation = Column(String(20))
    llm_review_reasoning = Column(Text)

    # Execution status
    status = Column(String(20), default='PENDING')
    executed_at = Column(DateTime)
    rejection_reason = Column(Text)

    # Timestamps
    first_signal_time = Column(DateTime, nullable=False)
    last_signal_time = Column(DateTime, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

    # Additional data
    signal_metadata = Column(Text)


class AgentAuditLog(Base):
    """Audit log for all agent decisions"""
    __tablename__ = "agent_audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    agent_name = Column(String(50), nullable=False, index=True)
    action_type = Column(String(50), nullable=False)
    symbol = Column(String(20))

    # Context
    input_snapshot = Column(JSON)
    decision = Column(JSON)
    reasoning = Column(Text)
    confidence = Column(Float)

    # Outcome
    status = Column(String(20))
    execution_time_ms = Column(Integer)

    created_at = Column(DateTime, default=datetime.utcnow, index=True)
