"""
Smart Trader Signal Model
"""
from sqlalchemy import Column, Integer, String, Float, DateTime, Text, Boolean, JSON
from datetime import datetime
from .database import Base


class SmartTraderSignal(Base):
    """Signals generated by Smart Trader system"""
    __tablename__ = "smart_trader_signals"
    
    id = Column(Integer, primary_key=True, index=True)
    
    # Signal identification
    composite_id = Column(String(100), unique=True, nullable=False, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    timeframe = Column(String(10), nullable=False)  # "5m", "15m", "1h", "1d"
    direction = Column(String(10), nullable=False)  # "LONG" or "SHORT"
    
    # Signal classification
    signal_families = Column(JSON)  # List of signal families
    signal_names = Column(JSON)  # List of signal names
    confluence_count = Column(Integer, nullable=False)
    aggregate_strength = Column(Float, nullable=False)
    
    # Confidence
    base_confidence = Column(Float, nullable=False)
    final_confidence = Column(Float, nullable=False)
    confidence_level = Column(String(10), nullable=False)  # "LOW", "MEDIUM", "HIGH"
    
    # Deterministic reasoning
    deterministic_reasons = Column(JSON)  # List of reasons from generators
    merged_features = Column(JSON)  # Combined features from all signals
    
    # LLM enhancement (optional)
    llm_confidence_adjustment = Column(Float)
    llm_narrative = Column(Text)
    llm_risk_flags = Column(JSON)  # List of risk flags
    llm_model = Column(String(50))
    llm_processing_time_ms = Column(Integer)
    
    # Trade setup (if constructed)
    entry_price = Column(Float)
    stop_loss = Column(Float)
    target = Column(Float)
    risk_reward_ratio = Column(Float)
    quantity = Column(Integer)
    
    # Trade review (if reviewed)
    llm_review_recommendation = Column(String(20))  # "APPROVE", "DOWNGRADE", "WAIT"
    llm_review_reasoning = Column(Text)
    
    # Execution status
    status = Column(String(20), default='PENDING')  # PENDING, EXECUTED, REJECTED, EXPIRED
    executed_at = Column(DateTime)
    rejection_reason = Column(Text)
    
    # Timestamps
    first_signal_time = Column(DateTime, nullable=False)
    last_signal_time = Column(DateTime, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    # Metadata
    metadata = Column(JSON)  # Additional data
